Repository DONGA-ST-B/frontend, pull requests merged in 2023-09, with the labels that each got.

#5 [Feat] : 구매 리스트 페이지 기본적인 컴포넌트 구현 (#3)
  .vscode/launch.json
  package-lock.json
  package.json
  src/assets/BuyBanner.png
  src/assets/LogoWhite.png
  src/components/buyList/BuyListButton.js
  src/components/footer/Footer.css
  src/components/footer/Footer.js
  src/pages/buyList/BuyBanner.js
  src/pages/buyList/BuyList.js
  src/pages/buyList/BuyListButtonGroup.js
  src/pages/buyList/BuyListPage.js
  src/routes/index.js
  src/styles/colors.js
Labels: 아린, ⚒️ feature

#7 [Feat] : 구매 리스트 페이지의 제품 리스트를 구체적으로 구현
  src/assets/BuyLike.png
  src/assets/BuyWish.png
  src/assets/ProductItem.png
  src/pages/buyList/BuyList.js
  src/pages/buyList/BuyListPage.js
  src/pages/buyList/ProductItem.js
  src/pages/product/ProductDetailPage.js
  src/routes/index.js
Labels: 아린, ⚒️ feature

#9 Feature/4#monitoring solution
  package-lock.json
  package.json
  src/assets/hicardi_logo.png
  src/assets/monitoring-solution-img.jpg
  src/assets/smartpatch.jpg
  src/components/header/ExHeader.html
  src/components/header/Header.js
  src/pages/monitoring/MonitoringInfo.js
  src/pages/monitoring/MonitoringPage.js
  src/pages/monitoring/SmartPatch.js
  src/routes/index.js
Labels: 채민, ⚒️ feature

#10 [Feat] : 구매 리스트의 배너를 구체적으로 구현
  package-lock.json
  package.json
  src/assets/BannerImage.png
  src/assets/BuyBannerBG.png
  src/pages/buyList/BannerTextBox.js
  src/pages/buyList/BuyBanner.js
  src/pages/buyList/BuyListPage.js
Labels: 아린, ⚒️ feature

#15 [feat] : add monitoring page1~3 (#4)
  src/assets/blue_circle.png
  src/assets/monitor.png
  src/assets/phone.png
  src/pages/monitoring/LiveStudio.js
  src/pages/monitoring/MonitoringInfo.js
  src/pages/monitoring/SmartPatch.js
  src/pages/monitoring/StatusMonitoring.js
Labels: 채민, ⚒️ feature

#16 [feat] : 4~7page UI
  src/assets/ion_chevron-back.svg
  src/assets/monitoring-table.png
  src/assets/telemetry_img.png
  src/assets/why1.png
  src/assets/why2.png
  src/assets/why3.png
  src/assets/why4.png
  src/pages/monitoring/LiveStudio.js
  src/pages/monitoring/MonitoringInfo.js
  src/pages/monitoring/Page5.js
  src/pages/monitoring/Telemetry.js
  src/pages/monitoring/Why.js
Labels: 채민, ⚒️ feature

#19 Feature/12#login basic
  src/assets/Google.png
  src/assets/Kakao.png
  src/assets/Naver.png
  src/components/header/Header.js
  src/pages/login/LoginButton.js
  src/pages/login/LoginInput.js
  src/pages/login/LoginPage.js
  src/pages/login/LoginTextBox.js
  src/pages/login/SocialButton.js
  src/pages/login/SocialGroup.js
  src/pages/product/ProductContainer.js
  src/pages/product/ProductDetailPage.js
  src/routes/index.js
  src/styles/colors.js
Labels: 아린, ⚒️ feature, 🔥 fix

#20 Feature/17#holter
  src/assets/holter1.png
  src/assets/holter_item.png
  src/assets/part3.png
  src/assets/part4-2.png
  src/assets/prat4-1.png
  src/pages/holter/HolterPage.js
  src/pages/holter/Part1.js
  src/pages/holter/Part2.js
  src/pages/holter/Part3.js
  src/pages/holter/Part4.js
  src/routes/index.js
Labels: 채민, ⚒️ feature

#21 [Feat] : 로그인 페이지 구현
  package-lock.json
  package.json
  src/pages/login/LoginBottom.js
  src/pages/login/LoginPage.js
  src/pages/login/SocialGroup.js
  src/routes/index.js
  src/styles/colors.js
Labels: 아린, ⚒️ feature

#23 [Feat] : 메인 페이지 기본 툴 구축
  src/pages/login/LoginPage.js
  src/pages/main/MainPage.js
  src/routes/index.js
Labels: 아린, ⚒️ feature

#24 Feature/17#holter
  src/assets/Table.png
  src/assets/data1.png
  src/assets/data2.png
  src/assets/data3.png
  src/assets/data4.png
  src/assets/icon1.png
  src/assets/icon2.png
  src/assets/icon3.png
  src/pages/holter/HolterPage.js
  src/pages/holter/Part5.js
  src/pages/holter/Part6.js
Labels: 채민, ⚒️ feature

#25 Feature/17#holter
  src/pages/holter/HolterPage.js
  src/pages/holter/Part7.js
  src/pages/holter/Part8.js
Labels: 채민, ⚒️ feature

#27 Feature/26#main chaemin
  src/assets/img1.png
  src/assets/img2.png
  src/assets/img3.png
  src/pages/main/Component4.js
  src/pages/main/MainPage.js
Labels: 채민, ⚒️ feature

#28 [Feat] 메인 컴포넌트 1-3 구현
  src/assets/About1.png
  src/assets/About2.png
  src/assets/About3.png
  src/assets/About4.png
  src/assets/Select1.png
  src/assets/Select2.png
  src/assets/Select3.png
  src/assets/Select4.png
  src/assets/Select5.png
  src/pages/main/MainAboutGroup.js
  src/pages/main/MainAboutItem.js
  src/pages/main/MainBanner.js
  src/pages/main/MainFirstText.js
  src/pages/main/MainPage.js
  src/pages/main/MainSelectGroup.js
  src/pages/main/MainSelectItem.js
  src/styles/colors.js
Labels: 아린, ⚒️ feature

#29 Feature/26#main chaemin
  package-lock.json
  package.json
  src/pages/main/Component5.js
  src/pages/main/MainPage.js
  src/pages/main/Temp.js
Labels: 채민, ⚒️ feature

#30 Feature/26#main chaemin
  src/components/header/ExHeader.html
  src/components/header/Header.js
  src/pages/main/Component5.js
Labels: 채민, ⚒️ feature

#34 [Hoxfix] : 메인 컴포넌트 넓이 조정
  package-lock.json
  package.json
  src/pages/main/MainAboutGroup.js
  src/pages/main/MainAboutItem.js
Labels: 아린, 🔥 fix
